[package]
name = "compute-reputation-graph"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "compute_reputation_graph"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.20.0", features = ["extension-module"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
tokio = { version = "1.9", features = ["macros", "rt-multi-thread"] }
rand = "0.8.5"
assert_approx_eq = "1.0"
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
serde = { version = "1.0.193", features = ["derive"] }
futures = "0.3.29"
