[package]
name = "compute-reputation-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "compute_reputation_graph"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.20.0", features = ["extension-module"] }
rand = "0.8.5"
assert_approx_eq = "1.0"
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
once_cell = "1.18.0"
async-std = "1.12.0"
